# Generated by Django 2.2.7 on 2019-11-14 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WishListItem1', models.TextField(blank=True, max_length=40)),
                ('WishListItem2', models.CharField(blank=True, max_length=40)),
                ('WishListItem3', models.CharField(blank=True, max_length=40)),
                ('SecretSanta', models.CharField(blank=True, max_length=40)),
                ('Gifter', models.CharField(blank=True, max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
