# Generated by Django 2.2.7 on 2019-11-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Gifter',
            new_name='Recipient',
        ),
        migrations.AddField(
            model_name='profile',
            name='SSWW1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='SSWW2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='SSWW3',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
