# Generated by Django 2.2.7 on 2019-11-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191115_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='SecretSanta',
            new_name='Gifter',
        ),
    ]
