# Generated by Django 2.2.7 on 2019-11-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_gifter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Gifter',
        ),
    ]
