# Generated by Django 2.2.7 on 2019-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_gifter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Gifter',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
