# Generated by Django 2.2.7 on 2019-11-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_gifter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Assigned',
        ),
    ]
