# Generated by Django 2.2.7 on 2019-11-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Assigned',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
