# Generated by Django 2.2.7 on 2019-11-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='AssignedEmail',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='SecretSantaEmail',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
